### ISSUE TITLE
Received data is encrypted

### ISSUE THREAD

**Issue by dineshbalu** [cepr/android-serialport-api#1]
Hi,
I have implemented this in my app , but when I was reading , the received data was different from what is sent.
There is no encryption done on sender end , it is just sending as it is ( verified it with windows terminal program )

Here is the response details
**Sent :** 954605E6
**Received :** ceٲVVM

**More conversions I tried:**
**Sent:**
Hex: 57 53 52 54 48 53 69 54
Decimal: 39 35 34 36 30 35 45 36
Binary : 00111001 00110101 00110100 00110110 00110000 00110101 01000101 00110110

**Received:**
Hex: 99 101 217 178 86 86 77 3
Decimal: 63 65 d9 b2 56 56 4d 03
Binary : 01100011 01100101 11011001 10110010 01010110 01010110 01001101 00000011

I don't have experience with this kind of communications

NOTE : Communication is via UART cable , app running in a custom device (HOwen , Hero)

Thank you

**Comment by specialshoot** [comment]
@dineshbalu The same to you.Do you know how solve this problem now?

**Comment by dineshbalu** [comment]
@specialshoot , It is fixed with change in different hardware connector ( cable ) , I don't remember what is it exactly. Will have to check with the hardware team. There is nothing wrong with the code though.

Sry about late response , didn't notice.

Thanks

**Comment by specialshoot** [comment]
Yes.I found it.Thanks.
